return {}
--     -- https://github.com/dense-analysis/neural
--     -- https://github.com/aduros/ai.vim
--
--     -- TODO:: These are interesting
--     -- https://github.com/folke/flash.nvim
--     -- https://github.com/quarto-dev/quarto-nvim
--     -- https://github.com/GnikDroy/projections.nvim
--     -- https://github.com/stevearc/overseer.nvim - A task runner and job management plugin for Neovim
--     -- https://github.com/ggandor/lightspeed.nvim --> move quickly
--     -- https://awesomeopensource.com/project/wellle/targets.vim --> move with f,F,t,T easier
--     -- https://github.com/danymat/neogen - Documentation generation
--     -- https://github.com/SmiteshP/nvim-navic - current code context
--     -- https://github.com/anuvyklack/windows.nvim
--     -- https://github.com/AckslD/nvim-FeMaco.lua
--     -- https://github.com/narutoxy/silicon.lua - screenshot code
--     --
--     -- https://github.com/williamboman/mason.nvim
--     -- https://github.com/p00f/clangd_extensions.nvim
--     --
--     -- https://github.com/jbyuki/venn.nvim - fancy diagrams
--     -- https://github.com/LudoPinelli/comment-box.nvim
--     --
--     -- https://github.com/theHamsta/nvim-dap-virtual-text
--     -- https://github.com/itchyny/calendar.vim
--     -- https://github.com/junegunn/fzf.vim
--     -- https://github.com/yuki-yano/fzf-preview.vim
--     -- https://github.com/kevinhwang91/rnvimr - Ranger in floating window
--     -- https://github.com/voldikss/vim-browser-search
--     -- https://github.com/kevinhwang91/nvim-bqf - better quickfix window
--     -- https://github.com/folke/which-key.nvim - shortcut hints
--     -- https://github.com/sbdchd/neoformat - if null-ls is not good enough
--     -- https://github.com/mattn/efm-langserver
--     -- https://awesomeopensource.com/project/wellle/context.vim
--     -- https://github.com/pearofducks/ansible-vim
--     -- https://github.com/vim-ctrlspace/vim-ctrlspace
--     -- https://github.com/unblevable/quick-scope - show header of current function, class, condition...
--     -- https://github.com/liuchengxu/vista.vim - View and search LSP symbols, tags
--     -- https://github.com/simrat39/symbols-outline.nvim
--     -- https://github.com/debugloop/telescope-undo.nvim
--     -- https://github.com/sotte/presenting.vim
